application: emcsquaredfraternity
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /(.*\.css)
  static_files: static/css/\1
  upload: static/css/(.*\.css)

- url: /(.*\.(gif|png|jpg|ico))
  static_files: static/images/\1
  upload: static/images/(.*\.(gif|png|jpg|ico))

- url: /.*
  script: handlers.main.app

libraries:
- name: jinja2
  version: latest

- name: webapp2
  version: "2.5.2"